select 'SELECT DISTINCT PC.CENARIO, PC.SEGMENTO, PC.DESCRICAO, CONTA, CICLO, KENAN_DB_ID'|| 
' FROM '|| OWNER ||'.'|| TABLE_NAME || ' CEN' ||
' JOIN PROATIVO_CENARIOS PC ON PC.ID_CENARIO = CEN.ID_CENARIO WHERE ID_EXECUCAO = ?;' COMANDO
from all_tables
where owner = 'PROATIVO_OWNER'
AND REGEXP_LIKE(TABLE_NAME, ? || '$')
AND TABLE_NAME LIKE '%_'||?||'_%'
AND REGEXP_LIKE(TABLE_NAME, '^CENARIO');